version: "3.9"

services:
  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: core.settings
      CELERY_BROKER_URL: redis://redis:6379/0
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      POSTGRES_HOST: postgres
      POSTGRES_DB: vrm_db
      POSTGRES_USER: vrm
      POSTGRES_PASSWORD: vrm
    depends_on:
      - redis
      - minio
      - postgres
    networks:
      - vrm_network

  worker:
    build: .
    command: celery -A core worker -l info
    volumes:
      - .:/app
    environment:
      DJANGO_SETTINGS_MODULE: core.settings
      CELERY_BROKER_URL: redis://redis:6379/0
      POSTGRES_HOST: postgres
      POSTGRES_DB: vrm_db
      POSTGRES_USER: vrm
      POSTGRES_PASSWORD: vrm
    depends_on:
      - redis
      - backend
    networks:
      - vrm_network

  beat:
    build: .
    command: celery -A core beat -l info
    volumes:
      - .:/app
    environment:
      DJANGO_SETTINGS_MODULE: core.settings
      CELERY_BROKER_URL: redis://redis:6379/0
      POSTGRES_HOST: postgres
      POSTGRES_DB: vrm_db
      POSTGRES_USER: vrm
      POSTGRES_PASSWORD: vrm
    depends_on:
      - redis
      - backend
      - worker
    networks:
      - vrm_network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - vrm_network

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    networks:
      - vrm_network

  postgres:
    image: postgres:15
    container_name: vrm_postgres
    environment:
      POSTGRES_USER: vrm
      POSTGRES_PASSWORD: vrm
      POSTGRES_DB: vrm_db
    ports:
      - "5432:5432"
    volumes:
      - vrm_postgres_data:/var/lib/postgresql/data
    networks:
      - vrm_network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - vrm_network

volumes:
  minio_data:
  vrm_postgres_data:

networks:
  vrm_network:
    driver: bridge
